### ISSUE TITLE
Will Type-C display port of the laptop work for connecting an external monitor as HDMI isnt working

### ISSUE THREAD

**Issue by saisurajch** [Ryuk-C/Hackintosh-OpenCore-Asus-FX506LH#1]

**Comment by Ryuk-C** [comment]
The issue with connecting an external monitor is not related to the Type-C or HDMI ports, but rather the Nvidia GTX 1650 GPU in this PC, which is used for screen sharing. Unfortunately, macOS does not support this version of the Nvidia GPU, so even if you try using the Type-C DisplayPort or HDMI port, macOS will not properly recognize the GPU. As a result, you won’t be able to use an external monitor with this system in a Hackintosh setup due to the lack of proper Nvidia drivers for macOS.
